version: '3.9'

services:
  #Aplicação (API)
  app:
    container_name: app
    image: app:latest
    build: .
    ports:
      - 3000:3000
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: database
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
     
    depends_on:
      - database

  #Banco de dados
  database:
    container_name: database
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    volumes:
      - pgdata:/var/lib/postgresql/data

  #pgAdmin
  pgadmin:
     container_name: pgadmin
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
       PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
     ports:
       - "8081:80"
     depends_on:
       - database
   
volumes:
  pgdata: {}